name: Check

on:
  push:
    branches:
      - main
      - pipeline-setup
  pull_request:
    branches:
      - main
      - pipeline-setup

permissions:
  contents: write

env:
  DOCS_REQ: docs/python-docs-requirements.txt
  MKDOCS_CONFIG: docs/mkdocs.yml

jobs:
# 1 ----------------------------------------------------------------------------------------------------
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Check make version
        run: make --version
        
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          
        
# 2 ----------------------------------------------------------------------------------------------------
  check_docker:
   runs-on: ubuntu-latest
   needs: setup 
   steps:
      - uses: actions/checkout@v4

      - name: make .env.stage file
        run: cp src/deployments/.env.stage.sample src/deployments/.env.stage

      - name: make .env.dev file
        run: cp src/deployments/.env.dev.sample env.dev

      - name: build docker dev image
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev build

            
      - name: upload env.dev as artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: env.dev

# 3 ----------------------------------------------------------------------------------------------------
  check_code:
    runs-on: ubuntu-latest
    needs: check_docker
    steps:
      - uses: actions/checkout@v4

      - name: get env.dev artifact
        uses: actions/download-artifact@v4
        with:
          name: env-file

      - name: start docker
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev up -d

      - name: containers
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev ps

      - name: logs
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev logs

      - name: sleep
        run: sleep 30

      - name: containers
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev ps
 
      - name: logs
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev logs

      - name: tests
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev exec pq-toolkit-api-dev make test

      - name: linter
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev exec pq-toolkit-api-dev make lint
       

# 4 ----------------------------------------------------------------------------------------------------
  cleanup:
    runs-on: ubuntu-latest
    needs: check_code
    
    steps:
      - uses: actions/checkout@v4

      - name: get env.dev artifact
        uses: actions/download-artifact@v4
        with:
          name: env-file


      - name: stop dev docker
        run: docker compose -f src/deployments/docker-compose.yml --env-file env.dev down